var _ = require('lodash');

var people = [{"id":1,"first_name":"Gussy","last_name":"Clymo","email":"gclymo0@skype.com","gender":"Female","ip_address":"107.70.27.207"},
    {"id":2,"first_name":"Paxon","last_name":"Scopham","email":"pscopham1@joomla.org","gender":"Male","ip_address":"156.133.97.217"},
    {"id":3,"first_name":"Persis","last_name":"Montacute","email":"pmontacute2@ucoz.ru","gender":"Female","ip_address":"66.210.195.39"},
    {"id":4,"first_name":"Paddie","last_name":"Rudgerd","email":"prudgerd3@geocities.com","gender":"Male","ip_address":"11.254.142.181"},
    {"id":5,"first_name":"Elwyn","last_name":"Castellani","email":"ecastellani4@tamu.edu","gender":"Male","ip_address":"54.190.65.47"},
    {"id":6,"first_name":"Enos","last_name":"Furphy","email":"efurphy5@prweb.com","gender":"Male","ip_address":"251.40.161.44"},
    {"id":7,"first_name":"Cesaro","last_name":"Lewin","email":"clewin6@un.org","gender":"Male","ip_address":"44.191.190.43"},
    {"id":8,"first_name":"Hinze","last_name":"Sprankling","email":"hsprankling7@technorati.com","gender":"Male","ip_address":"226.41.99.57"},
    {"id":9,"first_name":"Birch","last_name":"Courcey","email":"bcourcey8@whitehouse.gov","gender":"Male","ip_address":"175.245.69.238"},
    {"id":10,"first_name":"Antoine","last_name":"Shyram","email":"ashyram9@livejournal.com","gender":"Male","ip_address":"129.119.125.201"},
    {"id":11,"first_name":"Seka","last_name":"Krates","email":"skratesa@nationalgeographic.com","gender":"Female","ip_address":"42.117.33.115"},
    {"id":12,"first_name":"Arch","last_name":"Ruzek","email":"aruzekb@thetimes.co.uk","gender":"Male","ip_address":"15.165.165.104"},
    {"id":13,"first_name":"Lelah","last_name":"Tokley","email":"ltokleyc@vkontakte.ru","gender":"Female","ip_address":"154.44.5.164"},
    {"id":14,"first_name":"Claudelle","last_name":"Shillum","email":"cshillumd@pagesperso-orange.fr","gender":"Female","ip_address":"176.117.190.16"},
    {"id":15,"first_name":"Izzy","last_name":"Pettendrich","email":"ipettendriche@ezinearticles.com","gender":"Male","ip_address":"158.211.37.144"},
    {"id":16,"first_name":"Cassaundra","last_name":"Pentony","email":"cpentonyf@ezinearticles.com","gender":"Female","ip_address":"78.224.224.157"},
    {"id":17,"first_name":"Birgit","last_name":"Cleveley","email":"bcleveleyg@delicious.com","gender":"Female","ip_address":"106.140.191.146"},
    {"id":18,"first_name":"Ansell","last_name":"Morteo","email":"amorteoh@amazon.com","gender":"Male","ip_address":"165.133.146.199"},
    {"id":19,"first_name":"Everett","last_name":"O'Lynn","email":"eolynni@bbc.co.uk","gender":"Male","ip_address":"197.255.108.234"},
    {"id":20,"first_name":"Jana","last_name":"Medmore","email":"jmedmorej@sakura.ne.jp","gender":"Female","ip_address":"177.177.196.195"},
    {"id":21,"first_name":"Brody","last_name":"Le Teve","email":"bletevek@marriott.com","gender":"Male","ip_address":"252.53.165.28"},
    {"id":22,"first_name":"Obie","last_name":"Smallsman","email":"osmallsmanl@nih.gov","gender":"Male","ip_address":"77.123.245.63"},
    {"id":23,"first_name":"Cele","last_name":"Annable","email":"cannablem@ask.com","gender":"Female","ip_address":"198.255.168.19"},
    {"id":24,"first_name":"Mariejeanne","last_name":"Dellar","email":"mdellarn@answers.com","gender":"Female","ip_address":"232.53.110.44"},
    {"id":25,"first_name":"Lefty","last_name":"Solomonides","email":"lsolomonideso@stanford.edu","gender":"Male","ip_address":"74.235.81.225"},
    {"id":26,"first_name":"Sybyl","last_name":"Rowlinson","email":"srowlinsonp@gmpg.org","gender":"Female","ip_address":"87.198.136.253"},
    {"id":27,"first_name":"Petronia","last_name":"Gerren","email":"pgerrenq@cafepress.com","gender":"Female","ip_address":"250.114.197.160"},
    {"id":28,"first_name":"Marsha","last_name":"Haveline","email":"mhaveliner@facebook.com","gender":"Female","ip_address":"44.224.47.15"},
    {"id":29,"first_name":"Winny","last_name":"Jinkinson","email":"wjinkinsons@jiathis.com","gender":"Male","ip_address":"139.8.57.208"},
    {"id":30,"first_name":"Delbert","last_name":"Brenston","email":"dbrenstont@reddit.com","gender":"Male","ip_address":"115.31.176.117"},
    {"id":31,"first_name":"Aleen","last_name":"Struss","email":"astrussu@soup.io","gender":"Female","ip_address":"216.224.189.210"},
    {"id":32,"first_name":"Rosemarie","last_name":"Corss","email":"rcorssv@irs.gov","gender":"Female","ip_address":"29.167.193.166"},
    {"id":33,"first_name":"Benita","last_name":"Rewcassell","email":"brewcassellw@sun.com","gender":"Female","ip_address":"209.253.50.100"},
    {"id":34,"first_name":"Milena","last_name":"Enns","email":"mennsx@nature.com","gender":"Female","ip_address":"139.3.115.78"},
    {"id":35,"first_name":"Ashley","last_name":"Cullivan","email":"acullivany@dailymail.co.uk","gender":"Male","ip_address":"96.200.110.42"},
    {"id":36,"first_name":"Clarette","last_name":"Jantel","email":"cjantelz@netlog.com","gender":"Female","ip_address":"236.0.219.166"},
    {"id":37,"first_name":"Loretta","last_name":"Clougher","email":"lclougher10@simplemachines.org","gender":"Female","ip_address":"168.188.173.112"},
    {"id":38,"first_name":"Grant","last_name":"Pantridge","email":"gpantridge11@e-recht24.de","gender":"Male","ip_address":"23.232.92.250"},
    {"id":39,"first_name":"Mickey","last_name":"Harkin","email":"mharkin12@yellowpages.com","gender":"Male","ip_address":"218.156.0.26"},
    {"id":40,"first_name":"Moyra","last_name":"Lissimore","email":"mlissimore13@samsung.com","gender":"Female","ip_address":"183.190.27.148"},
    {"id":41,"first_name":"Denys","last_name":"Du Hamel","email":"dduhamel14@sfgate.com","gender":"Female","ip_address":"162.93.182.74"},
    {"id":42,"first_name":"Manny","last_name":"Dyble","email":"mdyble15@plala.or.jp","gender":"Male","ip_address":"237.39.130.186"},
    {"id":43,"first_name":"Lazar","last_name":"Selbach","email":"lselbach16@ehow.com","gender":"Male","ip_address":"77.252.207.204"},
    {"id":44,"first_name":"Loreen","last_name":"Livesay","email":"llivesay17@pagesperso-orange.fr","gender":"Female","ip_address":"130.63.98.150"},
    {"id":45,"first_name":"Clay","last_name":"Marten","email":"cmarten18@sogou.com","gender":"Male","ip_address":"167.116.103.238"},
    {"id":46,"first_name":"Nadia","last_name":"Bedinham","email":"nbedinham19@163.com","gender":"Female","ip_address":"167.202.89.73"},
    {"id":47,"first_name":"Artemus","last_name":"Handrok","email":"ahandrok1a@wp.com","gender":"Male","ip_address":"149.74.84.41"},
    {"id":48,"first_name":"Morey","last_name":"Bramich","email":"mbramich1b@shop-pro.jp","gender":"Male","ip_address":"108.150.119.167"},
    {"id":49,"first_name":"Murdock","last_name":"Erbe","email":"merbe1c@cyberchimps.com","gender":"Male","ip_address":"65.132.120.19"},
    {"id":50,"first_name":"Jordain","last_name":"Attwoul","email":"jattwoul1d@stumbleupon.com","gender":"Female","ip_address":"214.170.69.149"},
    {"id":51,"first_name":"Keri","last_name":"Jerrome","email":"kjerrome1e@simplemachines.org","gender":"Female","ip_address":"189.216.47.221"},
    {"id":52,"first_name":"Mace","last_name":"Belfit","email":"mbelfit1f@elegantthemes.com","gender":"Male","ip_address":"207.138.30.242"},
    {"id":53,"first_name":"Onfre","last_name":"Umney","email":"oumney1g@bloglines.com","gender":"Male","ip_address":"180.110.180.247"},
    {"id":54,"first_name":"Olympe","last_name":"McIlwrick","email":"omcilwrick1h@imdb.com","gender":"Female","ip_address":"14.251.170.234"},
    {"id":55,"first_name":"Johnathon","last_name":"Josofovitz","email":"jjosofovitz1i@freewebs.com","gender":"Male","ip_address":"50.178.235.49"},
    {"id":56,"first_name":"Nikkie","last_name":"Reina","email":"nreina1j@ameblo.jp","gender":"Female","ip_address":"5.105.238.53"},
    {"id":57,"first_name":"Barbe","last_name":"Ragat","email":"bragat1k@nhs.uk","gender":"Female","ip_address":"111.75.82.252"},
    {"id":58,"first_name":"Frazier","last_name":"Cattrall","email":"fcattrall1l@google.ru","gender":"Male","ip_address":"213.203.1.134"},
    {"id":59,"first_name":"Haleigh","last_name":"Rowbotham","email":"hrowbotham1m@discovery.com","gender":"Male","ip_address":"5.6.43.222"},
    {"id":60,"first_name":"Ranee","last_name":"Dodwell","email":"rdodwell1n@drupal.org","gender":"Female","ip_address":"156.241.236.2"}];

var femalePeople = _.filter(people,{gender:"Female"}).length;

alert(femalePeople);

